/**
 * One shared, camera-grounded human-face contract for every photoreal image and
 * video path. Wording is conditional so an environment/product-only scene does
 * not invent a person just because this lock is present.
 */
export const HUMAN_FACE_REALISM_LOCK =
  "HUMAN FACE REALISM LOCK (apply whenever a human face is visible): preserve one stable, age-appropriate facial topology — skull and face shape, forehead, temples, cheekbones, cheeks, jaw, chin, ears, nose, philtrum, lips, eyelids and natural left-right asymmetry never morph or become generically beautified. Skin must behave like living skin at the camera's real viewing distance: pore size and density vary by zone; fine vellus hair and follicles catch side/back light; faint capillaries, freckles, tiny blemishes, healed marks, under-eye texture, age-appropriate fine lines and subtle uneven tone remain; cheeks are softly matte while the T-zone and lips may carry restrained natural moisture; ears and nostril edges show gentle living translucency. Never erase texture with beauty smoothing. Eyes have off-white sclera with extremely subtle vessels, detailed iris fibres, round pupils, moist corneal catchlights, a real tear line and anatomically correct upper/lower eyelid folds. Eyebrows are made from separate rooted hairs with a believable growth direction, density gradient, tapered ends, small gaps and mild asymmetry — never a painted block, stamped arch or identical pair. Eyelashes grow individually from the eyelid margin: upper and lower lashes have varied length, spacing, curvature, direction, subtle clumping and tiny shadows; never a uniform fan, doll lashes, solid black strip or duplicated rows unless explicit cosmetic false lashes are part of the character. Nose skin keeps pores and soft cartilage transitions; lips retain fine vertical lines, natural edge softness and realistic hydration; visible teeth are naturally off-white with slight human variation, never a perfect glowing denture row. Hair preserves the exact hairline, temple shape, parting, density, colour, curl pattern and cut; show separate strands, root variation, limited scalp visibility at the part, baby hairs and a few flyaways with anisotropic natural sheen — never helmet hair, a solid plastic mass, wig-like edges or repeated clumps. Facial hair, when present, follows real follicle density and growth direction. Makeup, when requested, sits on top of this real anatomy and texture instead of replacing it. Keep all of these traits identical across frames and clips while expression changes only through anatomically plausible muscle movement.";

export const HUMAN_FACE_REALISM_NEGATIVE =
  "plastic, wax, porcelain or rubber skin, airbrushed poreless face, beauty-filter blur, excessive frequency separation, uniform pore noise, crunchy oversharpening, generic beautified face, facial topology drift, perfect bilateral symmetry, painted block eyebrows, stamped identical brows, missing brow hairs, solid-strip eyelashes, uniform doll-lash fan, duplicated lash rows, missing lower lashes, glass eyes, glowing white sclera, perfect denture teeth, helmet hair, plastic hair, wig edge, solid hair mass, repeated hair clumps, missing hairline, floating flyaway strands";

