import type { RuleEnforcement, RulePriority } from "./types.ts";
import type { CanonicalRuleOwner } from "./authority.ts";

export type RuleActivationMode = "currently_global" | "approved_script_only" | "product_only" | "intent_gated" | "context_gated" | "shot_gated";
export type RuleMigrationTarget = "keep_in_prompt" | "selective_prompt" | "compiler" | "validator" | "test_fixture";

export interface PromptRuleInventoryEntry {
  id: string;
  summary: string;
  source_anchor: string;
  current_owner: string;
  canonical_owner: CanonicalRuleOwner;
  priority: RulePriority;
  activation: RuleActivationMode;
  current_enforcement: readonly RuleEnforcement[];
  migration_target: readonly RuleMigrationTarget[];
  conflicts_with: readonly string[];
  rationale: string;
}

export const STORYBOARD_PROMPT_RULE_INVENTORY: readonly PromptRuleInventoryEntry[] = [
  { id: "storyboard.clip.continuous_take", summary: "Treat every generated clip as one continuous take with one primary action.", source_anchor: "storyboard-breakdown.ts#CRITICAL_PRODUCTION_MODEL", current_owner: "storyboard_system_prompt", canonical_owner: "prompt_compiler", priority: "conditional", activation: "currently_global", current_enforcement: ["prompt", "validator"], migration_target: ["selective_prompt", "validator"], conflicts_with: ["storyboard.editing.context_mode"], rationale: "Useful only when the selected clip/transition grammar requires one continuous generated take." },
  { id: "storyboard.editing.context_mode", summary: "Editing grammar follows the locked continuity/transition mode, including intentional montage or jump cuts.", source_anchor: "video-context/prompt.ts#multi-location-and-continuity-strategy", current_owner: "context_ir", canonical_owner: "cinematography", priority: "hard", activation: "context_gated", current_enforcement: ["analyzer", "compiler", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.clip.continuous_take"], rationale: "The locked transition mode decides which continuity restriction applies." },
  { id: "storyboard.hook.always_first_clip", summary: "Always reserve a 3-5 second Hook Window in the first clip.", source_anchor: "storyboard-breakdown.ts#PROJECT_LED_STORY_STRUCTURE", current_owner: "storyboard_system_prompt", canonical_owner: "scene_intent", priority: "conditional", activation: "currently_global", current_enforcement: ["prompt", "validator"], migration_target: ["selective_prompt", "validator"], conflicts_with: ["storyboard.hook.intent_gated"], rationale: "A hook cannot be universal for atmospheric, installation or experimental work." },
  { id: "storyboard.hook.intent_gated", summary: "Use a hook only when project intent or the approved script requires one.", source_anchor: "scene-intent/rules.ts#SCENE_INTENT_ABSTRACT_LAWS", current_owner: "scene_intent_rules", canonical_owner: "scene_intent", priority: "hard", activation: "intent_gated", current_enforcement: ["analyzer", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.hook.always_first_clip"], rationale: "Project intent owns whether attention must be earned as a formal hook." },
  { id: "storyboard.visible_text.forbid_all", summary: "Forbid every readable word, brand label and logo in generated video frames.", source_anchor: "storyboard-breakdown.ts#VIDEO_OUTPUT_TEXT_CONTRACT", current_owner: "storyboard_system_prompt", canonical_owner: "ontology", priority: "conditional", activation: "currently_global", current_enforcement: ["prompt", "validator"], migration_target: ["selective_prompt", "validator"], conflicts_with: ["storyboard.product.exact_label_lock", "storyboard.visible_text.context_policy"], rationale: "Generic suppression is safe only when higher-authority context/reference facts do not permit text." },
  { id: "storyboard.visible_text.context_policy", summary: "Apply the locked Context IR policy for diegetic text and overlays.", source_anchor: "video-context/types.ts#ContextOntologyLayer.visible_text_policy", current_owner: "context_ir", canonical_owner: "ontology", priority: "hard", activation: "context_gated", current_enforcement: ["analyzer", "compiler", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.visible_text.forbid_all"], rationale: "Locked ontology outranks the legacy global text ban." },
  { id: "storyboard.product.exact_label_lock", summary: "Preserve the exact verified product label, logo placement and brand colours.", source_anchor: "storyboard-breakdown.ts#FORENSIC_DNA_SCENE_BIBLE", current_owner: "storyboard_system_prompt", canonical_owner: "reference_authority", priority: "hard", activation: "product_only", current_enforcement: ["prompt", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.visible_text.forbid_all"], rationale: "Verified product reference outranks generic suppression on that product only." },
  { id: "storyboard.dialogue.reauthor", summary: "Elevate supplied dialogue into sharper, subtext-rich lines.", source_anchor: "storyboard-breakdown.ts#ROLE_LABELLED_DIALOGUE_RECOGNITION", current_owner: "storyboard_system_prompt", canonical_owner: "approved_script", priority: "conditional", activation: "currently_global", current_enforcement: ["prompt"], migration_target: ["selective_prompt"], conflicts_with: ["storyboard.dialogue.verbatim"], rationale: "Re-authoring belongs only to the explicit menu polish treatment." },
  { id: "storyboard.dialogue.verbatim", summary: "Preserve every current approved dialogue line with exact speaker ownership.", source_anchor: "storyboard-breakdown.ts#APPROVED_SCRIPT_STAGE_1", current_owner: "approved_script_block", canonical_owner: "approved_script", priority: "hard", activation: "approved_script_only", current_enforcement: ["prompt", "compiler", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.dialogue.reauthor"], rationale: "The menu-preserved original or completed creative revision owns current dialogue wording." },
  { id: "storyboard.performance.forced_business", summary: "Give every visible character a concrete hand action in every clip.", source_anchor: "storyboard-breakdown.ts#CHARACTER_BUSINESS", current_owner: "storyboard_system_prompt", canonical_owner: "scene_intent", priority: "preference", activation: "currently_global", current_enforcement: ["prompt"], migration_target: ["selective_prompt"], conflicts_with: ["storyboard.action.selective_budget"], rationale: "Business must serve objective/subtext and cannot overload every shot." },
  { id: "storyboard.action.selective_budget", summary: "Spend action and fidelity budget only on hero and causally interacted entities.", source_anchor: "video-context/prompt.ts#FIDELITY_IS_SELECTIVE", current_owner: "context_ir", canonical_owner: "physical_state", priority: "hard", activation: "shot_gated", current_enforcement: ["analyzer", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.performance.forced_business"], rationale: "A bounded action graph is more reliable than decorative motion for every visible person." },
  { id: "storyboard.camera.smooth_minimal", summary: "Use only smooth minimal camera movement and avoid large camera plus subject motion.", source_anchor: "storyboard-breakdown.ts#PHYSICAL_REALISM_CAMERA", current_owner: "storyboard_system_prompt", canonical_owner: "cinematography", priority: "conditional", activation: "currently_global", current_enforcement: ["prompt"], migration_target: ["selective_prompt"], conflicts_with: ["storyboard.camera.context_grammar"], rationale: "A useful stability profile, not the grammar for every genre." },
  { id: "storyboard.camera.context_grammar", summary: "Select camera motion from locked menu profile, genre, scene intent and continuity mode.", source_anchor: "video-context/prompt.ts#ONE_FACT_ONE_OWNER", current_owner: "context_ir", canonical_owner: "cinematography", priority: "hard", activation: "context_gated", current_enforcement: ["analyzer", "compiler", "validator"], migration_target: ["compiler", "validator"], conflicts_with: ["storyboard.camera.smooth_minimal", "storyboard.camera.forced_variety"], rationale: "Selected production profile and Context IR own camera grammar." },
  { id: "storyboard.camera.forced_variety", summary: "Rotate camera moves across clips and avoid repeating the same recipe.", source_anchor: "storyboard-breakdown.ts#CAMERA_VARIETY_ACROSS_CLIPS", current_owner: "storyboard_system_prompt", canonical_owner: "cinematography", priority: "preference", activation: "currently_global", current_enforcement: ["prompt"], migration_target: ["selective_prompt"], conflicts_with: ["storyboard.camera.context_grammar"], rationale: "Variety is secondary to selected grammar, intentional repetition and POV." },
  { id: "storyboard.physics.locked_mode", summary: "Physical behavior follows the locked world physics mode and declared exceptions.", source_anchor: "video-context/prompt.ts#REALITY_MODE_AND_FIDELITY_DEPTH", current_owner: "context_ir", canonical_owner: "world_context", priority: "hard", activation: "context_gated", current_enforcement: ["analyzer", "compiler", "validator"], migration_target: ["compiler", "validator"], conflicts_with: [], rationale: "Each chosen world needs internally consistent physics without being forced into realism." },
] as const;
