import jsPDF from "jspdf";

interface PdfScene {
  scene_number: number;
  title: string;
  description: string;
  dialogue: string | null;
  camera_angle: string;
  shot_type: string;
  mood: string;
  location: string;
  duration_seconds: number;
  image_url: string | null;
}

interface PdfInput {
  title: string;
  synopsis: string;
  scenes: PdfScene[];
}

export async function generateStoryboardPdf(
  input: PdfInput
): Promise<ArrayBuffer> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(28);
  doc.text(input.title, pageWidth / 2, 50, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  const synopsisLines = doc.splitTextToSize(input.synopsis, pageWidth - 80);
  doc.text(synopsisLines, pageWidth / 2, 70, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by StoryboardAI", pageWidth / 2, pageHeight - 15, {
    align: "center",
  });

  for (const scene of input.scenes) {
    doc.addPage();

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`Scene ${scene.scene_number}: ${scene.title}`, 15, 20);

    doc.setDrawColor(200, 200, 200);
    doc.line(15, 24, pageWidth - 15, 24);

    let yPos = 32;

    if (scene.image_url) {
      try {
        const response = await fetch(scene.image_url);
        const blob = await response.blob();
        const arrayBuffer = await blob.arrayBuffer();
        const base64 = Buffer.from(arrayBuffer).toString("base64");
        const imgData = `data:image/png;base64,${base64}`;

        const imgWidth = 160;
        const imgHeight = 90;
        doc.addImage(imgData, "PNG", 15, yPos, imgWidth, imgHeight);
        yPos += imgHeight + 8;
      } catch {
        doc.setFontSize(10);
        doc.setTextColor(200, 0, 0);
        doc.text("[Image not available]", 15, yPos + 10);
        yPos += 20;
      }
    }

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const descLines = doc.splitTextToSize(scene.description, pageWidth - 30);
    doc.text(descLines, 15, yPos);
    yPos += descLines.length * 5 + 4;

    if (scene.dialogue) {
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 150);
      const diaLines = doc.splitTextToSize(`"${scene.dialogue}"`, pageWidth - 30);
      doc.text(diaLines, 15, yPos);
      yPos += diaLines.length * 5 + 4;
    }

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    const meta = [
      `Camera: ${scene.camera_angle.replace(/_/g, " ")}`,
      `Shot: ${scene.shot_type.replace(/_/g, " ")}`,
      `Mood: ${scene.mood}`,
      `Location: ${scene.location}`,
      `Duration: ${scene.duration_seconds}s`,
    ].join("  |  ");
    doc.text(meta, 15, yPos);

    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(
      `StoryboardAI — Scene ${scene.scene_number}`,
      pageWidth - 15,
      pageHeight - 10,
      { align: "right" }
    );
  }

  return doc.output("arraybuffer");
}
