import JSZip from "jszip";

interface ZipScene {
  scene_number: number;
  title: string;
  image_url: string | null;
}

export async function generateStoryboardZip(
  title: string,
  scenes: ZipScene[]
): Promise<ArrayBuffer> {
  const zip = new JSZip();

  const imageFolder = zip.folder("scenes");
  if (!imageFolder) throw new Error("Failed to create zip folder");

  const downloadPromises = scenes
    .filter((s) => s.image_url)
    .map(async (scene) => {
      try {
        const response = await fetch(scene.image_url!);
        if (!response.ok) return;

        const blob = await response.blob();
        const arrayBuffer = await blob.arrayBuffer();
        const fileName = `scene_${String(scene.scene_number).padStart(2, "0")}_${scene.title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 30)}.png`;

        imageFolder.file(fileName, arrayBuffer);
      } catch {
        // Skip failed downloads
      }
    });

  await Promise.all(downloadPromises);

  const infoText = scenes
    .map(
      (s) =>
        `Scene ${s.scene_number}: ${s.title}${s.image_url ? "" : " [NO IMAGE]"}`
    )
    .join("\n");

  zip.file(
    "storyboard_info.txt",
    `${title}\nGenerated by StoryboardAI\n\n${infoText}`
  );

  return zip.generateAsync({ type: "arraybuffer" });
}
