// Environment archetype library — the app's locked "worlds", each with real
// material physics, Kelvin+Lux lighting, atmosphere and imperfections.
// Curated for this app's actual content: numerology shorts (varied outdoor
// metaphor locations per ngũ hành element), cooking (locked kitchen), fitness
// (locked gym), plus common story/ad interiors.

import type { EnvironmentArchetype, NguHanhElement } from "./types";

/** Baseline hard locks shared by every archetype (veoflow stability_constraints). */
const LOCKED = [
  "geometry_change",
  "material_change",
  "layout_rebuild",
  "palette_shift",
  "time_of_day_change",
  "weather_change",
];

export const environmentArchetypes: Record<string, EnvironmentArchetype> = {
  // ── EXTERIOR / NATURAL ────────────────────────────────────────────────────
  misty_mountain_ridge_dawn: {
    archetype_id: "misty_mountain_ridge_dawn",
    display_name: "Misty Mountain Ridge at Dawn",
    environment_class: "exterior_natural",
    element: "Thổ",
    keywords: ["mountain", "ridge", "mist", "peak", "cliff edge", "summit", "núi", "sống núi", "sương", "đỉnh", "mù sương", "bình minh trên núi"],
    scale: "open cliff-edge vista over layered fog-filled valleys, long sightlines to distant blue-grey peaks",
    materials: [
      { surface: "ground", material: "weathered grey rock with patches of dewy grass", physics: "matte, high roughness, damp dark patches, tiny embedded pebbles, no polish" },
      { surface: "midground", material: "forested slopes dissolving into fog layers", physics: "soft atmospheric perspective, saturation and contrast fall off with distance" },
      { surface: "sky", material: "soft overcast dawn sky with a warm horizon break", physics: "gentle luminous gradient, no banding, natural cloud texture" },
    ],
    lighting: { key_kelvin: 5200, ambient_kelvin: 6800, ambient_lux: 800, sources: ["soft overcast eastern sky", "warm horizon rim light"], shadows: "soft, diffused, cool blue-grey, imperfect edges, low contrast" },
    atmosphere: { time_of_day: "dawn / first light", weather: "cool, moist, calm", particulates: ["drifting fog wisps", "faint morning haze", "dew"], ambient_motion: "slow fog drift through the valley, gentle grass sway" },
    micro_details: ["dew beads on grass blades near the feet", "lichen patches on the rock", "a few wild seed-heads catching rim light"],
    imperfections: ["uneven rock cracks", "irregular fog density", "trampled grass at the ledge"],
    sound_bed: "soft mountain wind, faint distant birdsong, deep valley hush",
    micro_variation_allowed: ["fog drift", "grass sway", "subtle haze shift"],
    forbidden_variation: LOCKED,
  },

  open_field_sunrise: {
    archetype_id: "open_field_sunrise",
    display_name: "Open Grass Field at Sunrise",
    environment_class: "exterior_natural",
    element: "Mộc",
    keywords: ["field", "meadow", "sunrise", "grassland", "open plain", "cánh đồng", "đồng cỏ", "bình minh", "nắng sớm"],
    scale: "wide flat grassland to the horizon, single human figure reads clearly against low sun",
    materials: [
      { surface: "ground", material: "knee-high wild grass, mixed green-gold blades", physics: "individual blades translucent against low sun, matte earth beneath, dew wet" },
      { surface: "horizon", material: "tree line silhouette far away", physics: "hazy, low contrast, warm atmospheric glow" },
      { surface: "sky", material: "clear sunrise sky, gold to pale blue gradient", physics: "smooth natural gradient, sun disc soft, natural glare bloom only" },
    ],
    lighting: { key_kelvin: 3600, ambient_kelvin: 5600, ambient_lux: 2500, sources: ["low golden sun near the horizon", "cool blue open-sky fill"], shadows: "very long, soft-edged, warm-cool split tones" },
    atmosphere: { time_of_day: "sunrise / golden hour", weather: "clear, fresh, light breeze", particulates: ["backlit floating pollen and dust", "thin ground mist"], ambient_motion: "grass waves in the breeze, mist creeping low" },
    micro_details: ["spider-web threads catching sunlight", "dew flashing as the camera moves", "a worn dirt footpath through the grass"],
    imperfections: ["uneven grass height", "bare earth patches", "bent broken stalks"],
    sound_bed: "light breeze through grass, morning birds, distant open-air quiet",
    micro_variation_allowed: ["grass sway", "mist drift", "pollen sparkle"],
    forbidden_variation: LOCKED,
  },

  forest_morning_light: {
    archetype_id: "forest_morning_light",
    display_name: "Forest with Morning Light Shafts",
    environment_class: "exterior_natural",
    element: "Mộc",
    keywords: ["forest", "woods", "trees", "trail", "jungle", "rừng", "tán cây", "lối mòn", "cây xanh"],
    scale: "human-scale trail under tall canopy, medium sightlines broken by trunks",
    materials: [
      { surface: "ground", material: "packed earth trail with leaf litter and roots", physics: "matte damp soil, layered dry-wet leaves, roots polished by footsteps" },
      { surface: "verticals", material: "moss-covered bark on mature trunks", physics: "rough fibrous bark, velvet moss holding moisture, real depth" },
      { surface: "canopy", material: "layered green foliage", physics: "translucent backlit leaves, deep-shade greens, dappled gaps" },
    ],
    lighting: { key_kelvin: 5000, ambient_kelvin: 6500, ambient_lux: 1200, sources: ["sun shafts through canopy gaps", "cool green-bounced skylight"], shadows: "dappled, constantly soft-edged, moving slightly with the leaves" },
    atmosphere: { time_of_day: "mid-morning", weather: "fresh after light rain", particulates: ["visible light shafts", "floating spores and dust", "moisture in the air"], ambient_motion: "leaves trembling, light patches shifting slowly" },
    micro_details: ["fern fronds at path edge", "a fallen mossy log", "water drops falling from leaves occasionally"],
    imperfections: ["broken branches", "irregular trail width", "patches of mud with old bootprints"],
    sound_bed: "layered birdsong, leaves rustling, occasional water drips",
    micro_variation_allowed: ["leaf tremble", "light-shaft shimmer", "drip timing"],
    forbidden_variation: LOCKED,
  },

  lakeside_mist_dawn: {
    archetype_id: "lakeside_mist_dawn",
    display_name: "Still Lake with Dawn Mist",
    environment_class: "exterior_natural",
    element: "Thủy",
    keywords: ["lake", "water", "shore", "reflection", "river", "hồ", "mặt nước", "bờ hồ", "sông", "phản chiếu", "sương sớm"],
    scale: "wide mirror-still water plane, figure on a quiet stony shore, long horizontal sightlines",
    materials: [
      { surface: "water", material: "still dark lake water", physics: "near-mirror reflection broken by micro-ripples, real specular of sky, cold and deep" },
      { surface: "shore", material: "smooth wet stones and coarse sand", physics: "wet stones glossy, dry stones matte, dark waterline band" },
      { surface: "far bank", material: "tree line half-dissolved in mist", physics: "heavy atmospheric fade, blue-grey desaturation" },
    ],
    lighting: { key_kelvin: 6200, ambient_kelvin: 7000, ambient_lux: 900, sources: ["cool pre-sun sky dome", "pale warm glow at the east horizon"], shadows: "almost shadowless, soft ambient occlusion only" },
    atmosphere: { time_of_day: "dawn, before sunrise", weather: "windless, cold, humid", particulates: ["low mist sheets over the water", "breath fog in cold air"], ambient_motion: "mist sliding across the surface, slow ripple rings" },
    micro_details: ["a fish-rise ripple far out", "reeds standing in shallow water", "smooth skipping stones by the feet"],
    imperfections: ["driftwood on the shore", "uneven stone sizes", "waterline stains on rocks"],
    sound_bed: "near-silence, soft lapping water, a single distant bird call",
    micro_variation_allowed: ["mist drift", "ripple rings", "breath fog"],
    forbidden_variation: LOCKED,
  },

  coastal_cliff_sea_wind: {
    archetype_id: "coastal_cliff_sea_wind",
    display_name: "Coastal Cliff over Open Sea",
    environment_class: "exterior_natural",
    element: "Thủy",
    keywords: ["sea", "ocean", "cliff", "coast", "waves", "biển", "vách đá", "sóng", "đại dương", "gió biển"],
    scale: "high rocky headland over open sea, vast horizon, strong sense of height and wind",
    materials: [
      { surface: "cliff", material: "stratified sea-worn rock, salt-bleached", physics: "layered strata, sharp fractures softened by erosion, salt crust matte" },
      { surface: "sea", material: "deep blue-green open water with whitecaps", physics: "real wave motion with weight, foam trails dissolving, glinting sun path" },
      { surface: "ground", material: "wind-flattened coastal grass and bare rock", physics: "grass combed one direction by wind, rock polished at the edge" },
    ],
    lighting: { key_kelvin: 5600, ambient_kelvin: 6000, ambient_lux: 8000, sources: ["bright overcast-to-clear sea sky", "specular bounce off the water"], shadows: "medium-soft, slightly cool, wind-shaken grass shadows" },
    atmosphere: { time_of_day: "late afternoon", weather: "steady sea wind, bright", particulates: ["fine salt spray at the cliff base", "haze over far water"], ambient_motion: "continuous wave rollers, grass and jacket pressed by wind, gulls circling far off" },
    micro_details: ["foam bursting on rocks far below", "a weathered wooden marker post", "tiny yellow coastal flowers in rock cracks"],
    imperfections: ["crumbled cliff edge", "guano stains on lower rocks", "bent grass patches"],
    sound_bed: "steady sea wind, rhythmic distant waves, sparse gull cries",
    micro_variation_allowed: ["wave rhythm", "spray bursts", "grass flutter"],
    forbidden_variation: LOCKED,
  },

  sunset_winding_road: {
    archetype_id: "sunset_winding_road",
    display_name: "Winding Road at Sunset",
    environment_class: "exterior_urban",
    element: "Hỏa",
    keywords: ["road", "highway", "sunset", "crossroads", "path", "journey", "con đường", "ngã ba", "hoàng hôn", "đường vô tận", "chuyến đi"],
    scale: "empty two-lane road curving toward a burning horizon, very deep single-axis sightline",
    materials: [
      { surface: "road", material: "sun-aged asphalt with faded centre line", physics: "coarse aggregate texture, oily patch sheen, cracks with grass, warm bounce light" },
      { surface: "roadside", material: "dry golden brush and gravel shoulder", physics: "dusty matte, backlit stalks glowing at rim" },
      { surface: "sky", material: "layered sunset clouds, orange to deep violet", physics: "volumetric cloud edges lit from below, smooth banding-free gradients" },
    ],
    lighting: { key_kelvin: 3000, ambient_kelvin: 4500, ambient_lux: 1500, sources: ["low sun on the horizon dead ahead", "violet sky dome fill"], shadows: "extremely long, soft, stretching toward camera" },
    atmosphere: { time_of_day: "sunset / last light", weather: "dry, warm, still", particulates: ["golden dust in the air", "heat shimmer above the asphalt far away"], ambient_motion: "brush swaying lightly, shimmer wobble at the horizon" },
    micro_details: ["worn white line paint flaking", "a leaning kilometre marker", "power lines sagging between poles"],
    imperfections: ["tar repair snakes on the asphalt", "tire marks", "cracked shoulder edge"],
    sound_bed: "warm evening wind, distant crickets starting, deep open-road quiet",
    micro_variation_allowed: ["heat shimmer", "brush sway", "cloud drift"],
    forbidden_variation: LOCKED,
  },

  village_campfire_night: {
    archetype_id: "village_campfire_night",
    display_name: "Rural Village Campfire at Night",
    environment_class: "exterior_natural",
    element: "Hỏa",
    keywords: ["campfire", "fire", "night", "village", "bonfire", "lửa", "đống lửa", "bản làng", "đêm", "lửa trại"],
    scale: "intimate warm circle of firelight, darkness closing in beyond 5-6 metres",
    materials: [
      { surface: "fire", material: "real wood fire with glowing ember bed", physics: "flames with true volume and flicker, embers pulsing orange-red, occasional sparks rising and dying" },
      { surface: "ground", material: "packed dirt and flat sitting stones", physics: "warm bounce from the fire, matte dust, stone faces flickering" },
      { surface: "surroundings", material: "dark stilt-house silhouettes and trees", physics: "barely-lit rims only, deep natural blacks, no fake blue night wash" },
    ],
    lighting: { key_kelvin: 1900, ambient_kelvin: 4100, ambient_lux: 50, sources: ["campfire flicker from below-front", "thin cold moonlight rim"], shadows: "deep, dancing with the flames, warm-edged" },
    atmosphere: { time_of_day: "night", weather: "calm, cool", particulates: ["woodsmoke curling up", "sparks", "moths near the light"], ambient_motion: "flame flicker on every face and surface, smoke drift" },
    micro_details: ["a blackened kettle by the coals", "split firewood stacked", "woven mats around the circle"],
    imperfections: ["ash smears on stones", "half-burnt log ends", "uneven dirt"],
    sound_bed: "fire crackle and pops, night insects, occasional wood shift",
    micro_variation_allowed: ["flame flicker", "spark bursts", "smoke drift"],
    forbidden_variation: LOCKED,
  },

  // ── EXTERIOR / URBAN ──────────────────────────────────────────────────────
  city_rooftop_dusk: {
    archetype_id: "city_rooftop_dusk",
    display_name: "City Rooftop at Dusk",
    environment_class: "exterior_urban",
    element: "Kim",
    keywords: ["rooftop", "skyline", "city view", "dusk", "tòa nhà", "sân thượng", "thành phố", "nóc nhà", "đèn thành phố"],
    scale: "open rooftop terrace with low parapet, skyline panorama, city grid lights below",
    materials: [
      { surface: "floor", material: "grey concrete pavers with expansion gaps", physics: "matte, rain-stained, slight sheen where worn" },
      { surface: "parapet", material: "raw concrete ledge with steel rail", physics: "rough cast texture, rail paint chipped to metal at grip points" },
      { surface: "skyline", material: "glass towers against a fading sky", physics: "windows mixing warm interior lights and cold sky reflections, aircraft warning lights blinking" },
    ],
    lighting: { key_kelvin: 4500, ambient_kelvin: 3000, ambient_lux: 300, sources: ["last violet-blue daylight from the sky", "warm sodium-and-LED city glow from below"], shadows: "soft, double-toned (cool from sky, warm from city)" },
    atmosphere: { time_of_day: "dusk / blue hour", weather: "mild high-altitude breeze", particulates: ["thin urban haze", "distant heat vents steaming"], ambient_motion: "blinking tower lights, slow traffic streams far below, hair and jacket in light wind" },
    micro_details: ["HVAC units humming behind", "puddle from earlier rain reflecting the skyline", "cigarette-worn corner by the rail"],
    imperfections: ["rust streaks under the rail bolts", "patched waterproofing seams", "scattered gravel"],
    sound_bed: "soft city rumble far below, rooftop wind, faint AC hum",
    micro_variation_allowed: ["traffic light streams", "steam drift", "breeze gusts"],
    forbidden_variation: LOCKED,
  },

  urban_street_day: {
    archetype_id: "urban_street_day",
    display_name: "Vietnamese Shophouse Street, Daytime",
    environment_class: "exterior_urban",
    keywords: ["street", "shophouse", "sidewalk", "city street", "phố", "vỉa hè", "con phố", "nhà phố", "đường phố"],
    scale: "human-scale sidewalk along aged shophouses, deep street axis, light traffic presence",
    materials: [
      { surface: "sidewalk", material: "worn terrazzo and concrete tiles", physics: "cracked, patched, polished by decades of feet, matte with grime lines" },
      { surface: "facades", material: "sun-faded painted shophouse fronts", physics: "peeling layered paint, water stains under sills, hand-painted sign remnants" },
      { surface: "street", material: "aged asphalt", physics: "coarse, oil-darkened at the kerb, faded lane paint" },
    ],
    lighting: { key_kelvin: 5500, ambient_kelvin: 6000, ambient_lux: 9000, sources: ["high daylight sun with building-shade pockets", "cool sky fill in the shade"], shadows: "hard-edged in sun, soft in the covered sidewalk" },
    atmosphere: { time_of_day: "mid-morning", weather: "bright, warm", particulates: ["light street dust", "exhaust haze at the road"], ambient_motion: "passing motorbikes background blur, awnings flapping, tree shadows shifting" },
    micro_details: ["tangled power lines overhead", "a plastic stool cluster by a cafe door", "bicycle leaning on a pole"],
    imperfections: ["cracked tiles", "rust drips from balconies", "mismatched facade repairs"],
    sound_bed: "motorbike flow, street vendor calls far off, urban day ambience",
    micro_variation_allowed: ["traffic passing", "awning flutter", "pedestrian background"],
    forbidden_variation: LOCKED,
  },

  vietnam_highland_cook_spot: {
    archetype_id: "vietnam_highland_cook_spot",
    display_name: "Vietnamese Highland Outdoor Cooking Spot",
    environment_class: "exterior_natural",
    element: "Thổ",
    keywords: ["outdoor cooking", "wilderness cooking", "nấu ngoài trời", "nấu ăn trên núi", "đồi núi", "cao nguyên", "tây bắc", "hà giang", "asmr núi", "campfire cooking", "nướng ngoài trời"],
    scale: "a flat rock ledge used as the cooking station in the LOWER THIRD of frame, vast layered Vietnamese highland vista (grassy slopes, limestone karst ridges, drifting cloud) filling the upper frame",
    materials: [
      { surface: "cooking station", material: "thick olive-toned hardwood chopping board on a flat weathered rock", physics: "rich wood grain with knife marks and oil sheen, cool matte rock beneath, real weight — board never slides" },
      { surface: "ground", material: "wild highland grass, ochre and green, scattered stones", physics: "wind-combed blades, dew-damp earth, matte volcanic stones" },
      { surface: "backdrop", material: "layered Tây Bắc mountains and karst under a soft overcast sky", physics: "atmospheric perspective — each ridge fades bluer and softer with distance, drifting low cloud" },
      { surface: "fire", material: "small open wood fire with glowing coals and skewers", physics: "true flame flicker and heat shimmer, white smoke drifting with the wind, embers pulsing" },
    ],
    lighting: { key_kelvin: 6200, ambient_kelvin: 6800, ambient_lux: 6000, sources: ["soft overcast highland sky (giant natural softbox)", "warm glow from the coals when cooking over fire"], shadows: "very soft, almost shadowless daylight; warm underlight near the fire" },
    atmosphere: { time_of_day: "overcast late morning", weather: "cool highland air, steady light wind", particulates: ["drifting woodsmoke", "low cloud on far ridges", "occasional grass seeds in the wind"], ambient_motion: "grass rippling, smoke curling, clouds sliding slowly across the ridgeline" },
    micro_details: ["a hand-forged knife resting on the board", "a carved wooden bowl of dipping sauce", "banana leaf used as a plate", "steam rising off fresh-cut ingredients in the cold air"],
    imperfections: ["knife scars and stains on the board", "ash smudges on the rocks", "trampled grass around the cooking spot"],
    sound_bed: "steady highland wind, distant birds, fire crackle and pops, and CLOSE-MIC cooking ASMR — knife sliding through flesh onto wood, chop thuds, grating, drizzling, sizzling (no music, no voice)",
    micro_variation_allowed: ["smoke drift", "flame flicker", "cloud movement", "ingredient state as the recipe progresses"],
    forbidden_variation: LOCKED,
  },

  vietnam_stream_rock_cook: {
    archetype_id: "vietnam_stream_rock_cook",
    display_name: "Vietnamese Forest Stream Cooking Rock",
    environment_class: "exterior_natural",
    element: "Thủy",
    keywords: ["stream cooking", "bờ suối", "suối", "nấu bên suối", "rừng suối", "waterfall cooking", "asmr suối", "thác nước"],
    scale: "a broad flat mossy boulder as the cooking station beside a clear running stream, dense green Vietnamese forest and bamboo rising behind",
    materials: [
      { surface: "cooking station", material: "wide flat river boulder with a wooden chopping board", physics: "water-polished stone with wet dark patches, moss at the edges, board grain oiled and knife-marked" },
      { surface: "water", material: "clear shallow mountain stream over smooth pebbles", physics: "real flowing water with ripples, foam lines around rocks, glassy refraction to the pebble bed" },
      { surface: "backdrop", material: "layered jungle green — bamboo, ferns, broad-leaf trees, mist between trunks", physics: "wet leaves glisten, depth fades into cool green shade" },
    ],
    lighting: { key_kelvin: 5800, ambient_kelvin: 6500, ambient_lux: 3500, sources: ["diffused daylight filtered through the canopy", "cool bounce off the water"], shadows: "soft dappled, shifting gently with the leaves" },
    atmosphere: { time_of_day: "mid-morning", weather: "fresh, humid, cool by the water", particulates: ["fine water mist near ripples", "floating leaf fragments", "sun shafts through canopy gaps"], ambient_motion: "constant stream flow, leaves trembling, a butterfly passing" },
    micro_details: ["ingredients laid on a banana leaf", "a bamboo tube of spring water", "wet knife blade catching the light", "small fire ring of stacked stones nearby"],
    imperfections: ["moss patches and waterline stains on the boulder", "scattered wet pebbles", "a fallen branch in the stream"],
    sound_bed: "running stream water, layered forest birdsong, and CLOSE-MIC cooking ASMR — slicing, chopping on wood, rinsing in the stream, sizzling over the stone fire ring (no music, no voice)",
    micro_variation_allowed: ["water flow", "dappled light shimmer", "mist drift", "ingredient state as the recipe progresses"],
    forbidden_variation: LOCKED,
  },

  // ── INTERIORS ────────────────────────────────────────────────────────────
  vintage_cafe_interior: {
    archetype_id: "vintage_cafe_interior",
    display_name: "Vintage Cafe Nook",
    environment_class: "interior",
    element: "Thổ",
    keywords: ["cafe", "coffee shop", "coffee", "quán cà phê", "quán cafe", "cà phê", "góc quán"],
    scale: "cozy semi-open room ~10×8m, 3m pressed-tin ceiling, intimate table zones",
    materials: [
      { surface: "floor", material: "dark polished wood planks", physics: "worn matte traffic lanes, glossier under tables, real plank gaps" },
      { surface: "walls", material: "textured cream plaster with framed prints", physics: "hand-troweled unevenness, scuffs at chair height" },
      { surface: "furniture", material: "aged wood tables, brass fittings, worn upholstery", physics: "wood grain with cup rings, brass patinated dull except handles, fabric pilled at seat edges" },
    ],
    lighting: { key_kelvin: 3000, ambient_kelvin: 4500, ambient_lux: 250, sources: ["warm tungsten pendants", "soft daylight from a large arched window"], shadows: "soft, warm, layered from multiple small sources" },
    atmosphere: { time_of_day: "any (interior mood constant)", weather: "n/a", particulates: ["dust motes in the window light", "espresso steam wisps"], ambient_motion: "steam rising, background patrons subtly shifting, page turns" },
    micro_details: ["chalkboard menu with smudged eraser marks", "mismatched chairs", "small potted plants on the sill"],
    imperfections: ["scratched tabletops", "chipped paint on chair legs", "coffee ring stains"],
    sound_bed: "low cafe chatter, cup clinks, espresso machine hiss at -40dB feel",
    micro_variation_allowed: ["steam wisps", "background patron movement", "dust motes"],
    forbidden_variation: LOCKED,
  },

  warm_home_kitchen: {
    archetype_id: "warm_home_kitchen",
    display_name: "Warm Home Kitchen",
    environment_class: "interior",
    keywords: ["kitchen", "cooking", "stove", "counter", "bếp", "căn bếp", "nấu ăn", "gian bếp"],
    scale: "one fixed counter-and-stove wall, camera works within a 3m arc, tight warm framing",
    materials: [
      { surface: "counter", material: "oiled wooden chopping counter + stone worktop", physics: "knife-marked wood with oil sheen, cool honed stone, real crumb-scale texture" },
      { surface: "stove", material: "steel hob with cast-iron pan", physics: "brushed steel micro-scratches, pan seasoned black with use, real flame glow when lit" },
      { surface: "backsplash", material: "cream ceramic tiles", physics: "slight gloss, grout lines darkened near the hob, one hairline-cracked tile" },
    ],
    lighting: { key_kelvin: 4300, ambient_kelvin: 3200, ambient_lux: 600, sources: ["soft window daylight from the side", "warm under-cabinet strip"], shadows: "soft directional from the window, warm fill, appetising highlights on food" },
    atmosphere: { time_of_day: "late morning", weather: "n/a", particulates: ["cooking steam", "flour dust when active"], ambient_motion: "steam rising from the pan, curtain breathing at the window" },
    micro_details: ["worn wooden spoons in a jar", "fresh herbs in a glass", "a folded cloth by the hob"],
    imperfections: ["knife scars on the board", "a small burn mark by the hob", "water spots on steel"],
    sound_bed: "sizzling, chopping, gentle kitchen ambience (ASMR-clear, no music)",
    micro_variation_allowed: ["steam density", "flame flicker", "ingredient state as the recipe progresses"],
    forbidden_variation: LOCKED,
  },

  warm_apartment_living_room: {
    archetype_id: "warm_apartment_living_room",
    display_name: "Warm Apartment Living Room",
    environment_class: "interior",
    element: "Thổ",
    keywords: ["living room", "sofa", "couch", "apartment living", "phòng khách", "ghế sofa", "sô pha", "căn hộ", "chung cư"],
    scale: "one fixed sofa-and-TV wall zone ~5×4m, camera works within a 3.5m arc, warm domestic framing",
    materials: [
      { surface: "sofa", material: "fabric upholstery sofa with cushions", physics: "soft weave with seat compression creases, cushions dented where people actually sit, real fabric nap catching side light" },
      { surface: "floor", material: "warm wood-look flooring with a woven rug", physics: "satin plank sheen dulled along the walk path, rug fibres flattened where feet rest" },
      { surface: "furniture", material: "light wood coffee table + TV cabinet", physics: "visible grain, faint cup rings, matte edges slightly worn from daily use" },
    ],
    lighting: { key_kelvin: 4000, ambient_kelvin: 2700, ambient_lux: 450, sources: ["soft window daylight through sheer curtains", "warm practical floor and table lamps"], shadows: "soft directional from the window, warm pooled lamp light toward evening" },
    atmosphere: { time_of_day: "late afternoon into evening", weather: "n/a", particulates: ["faint dust motes in the window light"], ambient_motion: "sheer curtain breathing, plant leaves trembling near the fan, TV standby glow" },
    micro_details: ["a throw blanket folded over the sofa arm", "family photos and a small plant on the shelf", "TV remote and a glass of water on the coffee table"],
    imperfections: ["one flattened cushion", "a faint scuff at the table leg", "a slightly crooked photo frame"],
    sound_bed: "quiet apartment room tone, distant street murmur, soft clock tick, neighbours far off",
    micro_variation_allowed: ["curtain sway", "lamp warmth", "TV standby glow"],
    forbidden_variation: LOCKED,
  },

  modern_gym_daylight: {
    archetype_id: "modern_gym_daylight",
    display_name: "Modern Gym with Daylight",
    environment_class: "interior",
    keywords: ["gym", "workout", "fitness", "training", "phòng gym", "phòng tập", "tập luyện", "thể hình"],
    scale: "one fixed training corner: rubber floor, rack and mirror wall, 4m working area",
    materials: [
      { surface: "floor", material: "black rubber tiles with grey fleck", physics: "matte grippy texture, chalk dust residue, plate-drop dents" },
      { surface: "equipment", material: "powder-coated steel rack, knurled bars, iron plates", physics: "knurling worn shiny at grip zones, plate edges chipped to bare metal, real weight on every move" },
      { surface: "mirror wall", material: "floor-to-ceiling mirrors", physics: "true reflections with slight seam lines, hand smudges at touch height" },
    ],
    lighting: { key_kelvin: 5000, ambient_kelvin: 6000, ambient_lux: 700, sources: ["high side windows daylight", "neutral LED panels"], shadows: "medium-soft, clean but never clinical, honest sweat sheen highlights" },
    atmosphere: { time_of_day: "morning session", weather: "n/a", particulates: ["chalk dust puffs on grip", "faint air-con drift"], ambient_motion: "background plates being re-racked far off, fan oscillation" },
    micro_details: ["chalk block in a bowl", "a towel over the rack pin", "water bottle with condensation"],
    imperfections: ["scuffed floor lanes", "mismatched old plates", "taped bar sleeve"],
    sound_bed: "controlled breathing, plates settling, low gym room tone",
    micro_variation_allowed: ["chalk dust", "breathing rhythm", "background member far off"],
    forbidden_variation: LOCKED,
  },

  quiet_night_office: {
    archetype_id: "quiet_night_office",
    display_name: "Quiet Office at Night",
    environment_class: "interior",
    element: "Kim",
    keywords: ["office", "desk", "overtime", "laptop", "văn phòng", "bàn làm việc", "tăng ca", "đêm khuya làm việc"],
    scale: "one desk island lit in a dark open-plan floor, city bokeh through the window wall",
    materials: [
      { surface: "desk", material: "laminate desktop with paper stacks", physics: "micro-scratches catching lamp light, matte papers, glossy screen" },
      { surface: "window wall", material: "full-height glazing over the city", physics: "double reflection: interior lamp ghost + city lights bokeh, slight dust film" },
      { surface: "floor", material: "dark carpet tiles", physics: "light-absorbing, worn path to the desk" },
    ],
    lighting: { key_kelvin: 3800, ambient_kelvin: 6500, ambient_lux: 180, sources: ["single warm desk lamp", "cold monitor glow on the face", "city glow through glass"], shadows: "pooled darkness beyond the desk, soft warm core light" },
    atmosphere: { time_of_day: "late night", weather: "n/a", particulates: ["faint dust in the lamp cone"], ambient_motion: "cursor blink reflected in the eyes, distant elevator hum" },
    micro_details: ["cold coffee with a dried ring", "sticky notes on the monitor edge", "jacket over the chair back"],
    imperfections: ["cable tangle", "one dead ceiling tile light far off", "smudged glass"],
    sound_bed: "deep building hum, AC whisper, occasional keyboard taps",
    micro_variation_allowed: ["monitor glow shifts", "city light twinkle"],
    forbidden_variation: LOCKED,
  },

  minimal_glass_studio: {
    archetype_id: "minimal_glass_studio",
    display_name: "Minimal Glass & Concrete Studio",
    environment_class: "interior",
    element: "Kim",
    keywords: ["studio", "minimal", "glass", "modern interior", "showroom", "phòng trưng bày", "tối giản", "kính", "hiện đại"],
    scale: "clean open room, polished floor, one glass wall of soft daylight, generous negative space",
    materials: [
      { surface: "floor", material: "polished micro-cement", physics: "satin sheen with soft reflections, trowel swirl marks visible at angle" },
      { surface: "walls", material: "raw board-formed concrete", physics: "wood-grain imprint, formwork tie holes, honest grey variation" },
      { surface: "glass wall", material: "floor-to-ceiling frosted-clear glazing", physics: "soft diffused daylight, faint mullion shadows" },
    ],
    lighting: { key_kelvin: 5000, ambient_kelvin: 5600, ambient_lux: 450, sources: ["large diffused window wall", "recessed neutral spots"], shadows: "very soft, precise but natural falloff" },
    atmosphere: { time_of_day: "daytime", weather: "n/a", particulates: ["almost none — clean air, rare dust sparkle at the glass"], ambient_motion: "nearly still; light shifts slowly with clouds" },
    micro_details: ["a single designer chair", "hairline shadow gap at wall-floor joint", "one green plant for scale"],
    imperfections: ["concrete patch tone differences", "tiny floor pinholes"],
    sound_bed: "hushed room tone, soft footstep acoustics with short natural decay",
    micro_variation_allowed: ["cloud-driven light shifts"],
    forbidden_variation: LOCKED,
  },
};

/** Ngũ hành element → environment archetype ids (for numerology videos). */
export const elementToArchetypes: Record<NguHanhElement, string[]> = {
  "Thủy": ["lakeside_mist_dawn", "coastal_cliff_sea_wind", "vietnam_stream_rock_cook", "misty_mountain_ridge_dawn"],
  "Thổ": ["misty_mountain_ridge_dawn", "vintage_cafe_interior", "vietnam_highland_cook_spot", "village_campfire_night"],
  "Mộc": ["forest_morning_light", "open_field_sunrise"],
  "Kim": ["minimal_glass_studio", "city_rooftop_dusk", "quiet_night_office"],
  "Hỏa": ["village_campfire_night", "sunset_winding_road"],
};

export const environmentLibrary = {
  version: "1.0",
  archetypes: environmentArchetypes,
  elementToArchetypes,
};
