import type { StoryboardGenerationInput, VideoGoal } from "@/types";

// ─── Marketing templates ────────────────────────────────────────────────────

const GOAL_GUIDANCE: Record<VideoGoal, string> = {
  marketing_general:
    "General marketing short. Strong 3-second hook, build desire, end with a clear CTA.",
  product_ad:
    "Product advertisement. Show the product in use, highlight 2-3 key benefits, demonstrate the result, end with a buy/visit CTA.",
  storytelling:
    "Narrative story. Relatable character, a tension/conflict, a turning point, an emotional payoff, subtle CTA.",
  review:
    "Honest review/testimonial. Hook with the verdict, show pros, show one con, give recommendation CTA.",
  educational:
    "Educational/how-to. Hook with the problem/promise, deliver clear steps, recap, follow-for-more CTA.",
};

// ─── Step 1: Segment Breakdown + Character Lock ─────────────────────────────

export function buildStoryboardSystemPrompt(): string {
  return `You are a world-class short-form video director and marketing strategist. You design storyboards that are turned into REAL videos using AI image-to-video tools (Google Veo 3, Seedance, Kling).

CRITICAL PRODUCTION MODEL — how the final video is actually made:
- The video is assembled from multiple ~8-second CLIPS ("segments").
- Each 8s segment contains a FAST 3-SHOT SEQUENCE (3 distinct shots/scenes that cut quickly within the 8 seconds) — never a single static scene dragging for 8s. This keeps pacing tight, saves cost (3 scenes in one generation), and works with Seedance/Veo multi-shot.
- Each segment is generated by feeding its 3-shot storyboard + ONE multi-shot motion prompt into Veo/Seedance.
- Segments are CHAINED for seamless playback: the visual state at the END of segment N must flow naturally into the START of segment N+1 (same character, location, lighting, continuous action). No jarring cuts between segments.
- So "beats" = the 3 shots inside an 8s segment. Provide EXACTLY 3 beats per segment.

MARKETING STRUCTURE (always apply):
- HOOK in the first segment (grab attention in 3 seconds).
- Then PROBLEM → SOLUTION → (optional BODY beats) → CTA in the final segment.
- Reset attention every 5-8 seconds with an angle change, push-in, or reveal.

CHARACTER CONSISTENCY:
- Build a detailed "character_lock" per character; it is restated in every image prompt.
- Keep wardrobe, face, and props identical across all segments.

Camera codes: [EYE] eye-level, [LOW] low, [HIGH] high, [OVH] overhead, [DUTCH] dutch, [OTS] over-shoulder, [POV] first-person, [CLOSE] close-up, [SIDE] side profile.

Output MUST be valid JSON only — no markdown, no code fences, no text outside the JSON.`;
}

export function buildStoryboardUserPrompt(
  input: StoryboardGenerationInput
): string {
  const characterBlock =
    input.character_descriptions && input.character_descriptions.length > 0
      ? `\n\nCharacters:\n${input.character_descriptions.map((c) => `- ${c.name}: ${c.appearance}. Personality: ${c.personality}. Role: ${c.role}`).join("\n")}`
      : "";

  const settingBlock = input.setting ? `\nPrimary Setting: ${input.setting}` : "";
  const toneBlock = input.tone ? `\nTone: ${input.tone}` : "";
  const customBlock = input.custom_instructions
    ? `\nAdditional Instructions: ${input.custom_instructions}`
    : "";

  const segmentCount = input.segment_count ?? 5;
  const goal = input.video_goal ?? "marketing_general";
  const goalGuidance = GOAL_GUIDANCE[goal];

  return `Create a chained-segment storyboard for this short video.

Story / Product Idea: ${input.story_idea}
Video Goal: ${goal} — ${goalGuidance}
Genre: ${input.genre}
Visual Style: ${input.style}
Number of 8-second SEGMENTS: ${segmentCount} (total ≈ ${segmentCount * 8} seconds)${characterBlock}${settingBlock}${toneBlock}${customBlock}

Produce EXACTLY ${segmentCount} segments. Each segment = one 8s clip containing EXACTLY 3 quick shots (3 beats). Segment 1 must HOOK. The last segment must contain the CTA. Make every segment END in a state that flows seamlessly into the next segment's START. The "motion_prompt" must describe the 3-shot sequence in order with rough timing (e.g. "0-3s ...; 3-5s ...; 5-8s ..."), camera moves, and how the clip ends so it leads into the next segment.

Return a JSON object with this EXACT structure:
{
  "title": "string — catchy title",
  "synopsis": "string — 2-3 sentences",
  "total_duration_seconds": ${segmentCount * 8},
  "mood_tags": ["3-4 mood keywords"],
  "marketing_structure": {
    "hook": "string — the 3s hook line/idea",
    "problem": "string — the pain point addressed",
    "solution": "string — how it is solved/shown",
    "cta": "string — the final call to action"
  },
  "character_locks": [
    {
      "name": "string",
      "gender_age": "string",
      "build": "string",
      "skin_tone": "string",
      "hair": "string",
      "eyes": "string",
      "costume": "string",
      "signature_features": "string",
      "default_expression": "string",
      "render_style": "${input.style}"
    }
  ],
  "segments": [
    {
      "segment_number": 1,
      "duration_seconds": 8,
      "title": "string — short segment title",
      "marketing_role": "hook|problem|solution|body|cta",
      "beats": [
        { "beat": "shot 1 action", "camera": "[WIDE] ..." },
        { "beat": "shot 2 action", "camera": "[CLOSE] ..." },
        { "beat": "shot 3 action", "camera": "[OTS] ..." }
      ],
      "first_frame_prompt": "string — describe the SHARED scene/setting of this 8s segment (location, lighting, character appearance, product if any). Used to render the 3-shot storyboard strip.",
      "motion_prompt": "string — 40-80 word multi-shot image-to-video prompt for Veo/Seedance covering the 3 shots with rough timing (e.g. '0-3s ...; 3-5s ...; 5-8s ...'), camera moves, and an ending that leads into the next segment.",
      "dialogue": "string or null — spoken line / voiceover",
      "continuity_note": "string — how this segment visually continues from the previous segment (for segment 1 write 'opening shot')"
    }
  ],
  "style_guide": {
    "color_palette": ["5-7 hex colors"],
    "art_direction": "string",
    "visual_references": "string",
    "consistency_notes": "string"
  }
}`;
}

// ─── Render style helpers ───────────────────────────────────────────────────

const PHOTO_STYLES = new Set(["realistic", "cinematic"]);

export function isPhotoStyle(style: string): boolean {
  return PHOTO_STYLES.has(style);
}

function renderDirective(style: string, preserveRealFace: boolean): string {
  if (isPhotoStyle(style)) {
    return `Photorealistic, lifelike, real human, cinematic photography quality — NOT a cartoon, NOT an illustration.${
      preserveRealFace
        ? " CRITICAL: preserve the EXACT real face, skin tone, hairstyle and likeness from the attached reference photo. Keep it the same real person, do NOT stylize the face into a cartoon."
        : ""
    }`;
  }
  return `${style} art style.${
    preserveRealFace
      ? " Keep the person's real facial structure and likeness recognizable from the reference photo, rendered in this art style."
      : ""
  }`;
}

// ─── Step 2: Character Reference Sheet Image Prompt ─────────────────────────

export function buildCharacterRefSheetPrompt(params: {
  characterLock: {
    name: string;
    gender_age: string;
    build: string;
    skin_tone: string;
    hair: string;
    eyes: string;
    costume: string;
    signature_features: string;
    default_expression: string;
    render_style: string;
  };
  props?: string[];
  colorPalette?: string[];
  style?: string;
  preserveRealFace?: boolean;
}): string {
  const c = params.characterLock;
  const style = params.style ?? c.render_style;
  const directive = renderDirective(style, params.preserveRealFace ?? false);

  const colorSwatches =
    params.colorPalette && params.colorPalette.length > 0
      ? params.colorPalette.slice(0, 6).join(", ")
      : "#F5E6D3, #8B4513, #2D5016, #FFFFFF, #1A1A1A, #D4A574";

  return `Professional CHARACTER REFERENCE SHEET, single horizontal image, clean light studio background.

CHARACTER — ${c.name}: ${c.gender_age}, ${c.build} build, ${c.skin_tone} skin, ${c.hair} hair, ${c.eyes} eyes. Wearing ${c.costume}. ${c.signature_features}.

EXACT LAYOUT (all in one image):
■ LEFT ZONE: Large FULL BODY hero pose, ${c.default_expression} expression, head to toe.
■ CENTER: "TURNAROUND" — 4 full-body views: FRONT, 3/4, SIDE, BACK; same scale, neutral pose, evenly lit, labeled.
■ TOP-RIGHT: "EXPRESSIONS" — 6 head portraits 3×2 grid: HAPPY, CALM, SURPRISED, CONFIDENT, THOUGHTFUL, FRIENDLY.
■ BOTTOM-RIGHT: "COLOR PALETTE" — 6 circular swatches: ${colorSwatches}.

${directive}

RULES: it must be the SAME individual in every zone with identical face; small bold labels; one cohesive image.`;
}

// ─── Step 3: Per-Segment Storyboard Strip (3 shots in one 8s clip) ──────────

export function buildSegmentFirstFramePrompt(params: {
  segmentNumber: number;
  firstFramePrompt: string;
  beats: { beat: string; camera: string }[];
  characterDescription: string;
  style: string;
  isFirst: boolean;
  preserveRealFace?: boolean;
}): string {
  const directive = renderDirective(params.style, params.preserveRealFace ?? false);

  const beats = params.beats.slice(0, 3);
  while (beats.length < 3) {
    beats.push({ beat: params.firstFramePrompt, camera: "[EYE]" });
  }
  const panelLines = beats
    .map((b, i) => `Panel ${i + 1} (${b.camera}): ${b.beat}`)
    .join("\n");

  const continuity = params.isFirst
    ? "Panel 1 is the opening shot of the whole video."
    : "Panel 1 must continue seamlessly from the previous segment's final shot (same character, wardrobe, lighting, location).";

  return `STORYBOARD STRIP for ONE ~8 second video clip: a single horizontal image split into 3 EQUAL panels side by side, showing a fast 3-shot sequence (left → right) that plays within the 8 seconds. ${params.style} style.

CHARACTER (identical face in every panel): ${params.characterDescription}

SCENE CONTEXT: ${params.firstFramePrompt}

THE 3 PANELS (left to right):
${panelLines}

${continuity}
${directive}

Each panel: a small number (1, 2, 3) in the top-left corner, distinct camera framing per its note, thin clean divider lines between panels. The SAME individual with the SAME face/outfit across all 3 panels. No captions, no subtitles, no watermark.`;
}

// ─── Step 4: Storyboard Overview Poster (presentation) ──────────────────────

export function buildStoryboardPosterPrompt(params: {
  title: string;
  totalDuration: number;
  segmentCount: number;
  moodTags: string[];
  segments: {
    segment_number: number;
    title: string;
    summary: string;
    role: string;
  }[];
  characterDescription: string;
  style: string;
  colorPalette?: string[];
}): string {
  const maxPanels = Math.min(params.segments.length, 12);
  const panels = params.segments.slice(0, maxPanels);

  const cols = maxPanels <= 6 ? 3 : 4;
  const rows = Math.ceil(maxPanels / cols);

  const panelLines = panels
    .map((s) => {
      const short = s.summary.length > 50 ? s.summary.slice(0, 50) + "..." : s.summary;
      return `[${s.segment_number}] "${s.title}" (${s.role}): ${short}`;
    })
    .join("\n");

  const charDesc =
    params.characterDescription.length > 300
      ? params.characterDescription.slice(0, 300) + "..."
      : params.characterDescription;

  const colorBlock =
    params.colorPalette && params.colorPalette.length > 0
      ? `Color palette: ${params.colorPalette.join(", ")}.`
      : "";

  return `Professional STORYBOARD overview poster, single horizontal image, clean white/cream background.

CHARACTER (identical in every panel): ${charDesc}

HEADER: bold title "STORYBOARD" left; subtitle "${params.title}" center; right metadata "${params.totalDuration}s • ${maxPanels} segments • ${params.moodTags.slice(0, 4).join(" • ")}".

PANEL GRID: ${cols} columns × ${rows} rows, thin black borders. Each panel: numbered badge top-left, ${params.style} illustration of the segment, 1-line italic caption below.

PANELS:
${panelLines}

RULES: ONE single image with ALL ${maxPanels} panels; same character across panels; ${params.style} style; ${colorBlock} clean production-document look; numbered badges visible.`;
}

// ─── Step 5: Video Assembly Guide (text for Veo / Seedance) ─────────────────

export function buildVideoPromptText(params: {
  title: string;
  characterDescription: string;
  setting: string;
  style: string;
  aspectRatio: string;
  colorPalette: string[];
  marketing: { hook: string; problem: string; solution: string; cta: string };
  segments: {
    segment_number: number;
    title: string;
    role: string;
    duration_seconds: number;
    motion_prompt: string;
    dialogue?: string | null;
    continuity_note: string;
    beats: { beat: string; camera: string }[];
  }[];
}): string {
  const totalDuration = params.segments.reduce(
    (sum, s) => sum + s.duration_seconds,
    0
  );

  const segLines = params.segments
    .map((s) => {
      const beats = s.beats
        .map((b) => `      • ${b.camera} — ${b.beat}`)
        .join("\n");
      return `SEGMENT ${s.segment_number} — "${s.title}" [${s.role.toUpperCase()}] (${s.duration_seconds}s)
  Beats:
${beats}
  Motion prompt (paste into Veo/Seedance image-to-video):
    ${s.motion_prompt}${s.dialogue ? `\n  Voiceover/Dialogue: "${s.dialogue}"` : ""}
  Continuity: ${s.continuity_note}`;
    })
    .join("\n\n");

  return `# VIDEO ASSEMBLY GUIDE — ${params.title}
Total length ≈ ${totalDuration}s · ${params.segments.length} segments · ${params.aspectRatio} · ${params.style}

## Marketing arc
- HOOK: ${params.marketing.hook}
- PROBLEM: ${params.marketing.problem}
- SOLUTION: ${params.marketing.solution}
- CTA: ${params.marketing.cta}

## Character (keep identical in every clip)
${params.characterDescription}

## Setting
${params.setting}
Color palette: ${params.colorPalette.join(", ")}

## HOW TO BUILD THE VIDEO (seamless chaining)
1. For each segment, upload its FIRST-FRAME image to Veo/Seedance (image-to-video) and paste its motion prompt. Set aspect ratio ${params.aspectRatio}.
2. To join clips seamlessly: use the LAST frame of clip N as the start image of clip N+1, OR use Veo "Extend". Each segment's start frame is already designed to continue the previous one.
3. Generate all ${params.segments.length} clips, then stitch them in order (CapCut/ffmpeg). Add the voiceover lines and the CTA end card.

## SEGMENTS
${segLines}

---
Compatible with: Google Veo 3.1, Seedance 2.0, Kling, Runway, Pika`;
}
