import type { StoryboardGenerationInput, VideoGoal } from "@/types";

// ─── Marketing templates ────────────────────────────────────────────────────

const GOAL_GUIDANCE: Record<VideoGoal, string> = {
  marketing_general:
    "General marketing short. Strong 3-second hook, build desire, end with a clear CTA.",
  product_ad:
    "Product advertisement. Show the product in use, highlight 2-3 key benefits, demonstrate the result, end with a buy/visit CTA.",
  storytelling:
    "Narrative story. Relatable character, a tension/conflict, a turning point, an emotional payoff, subtle CTA.",
  review:
    "Honest review/testimonial. Hook with the verdict, show pros, show one con, give recommendation CTA.",
  educational:
    "Educational/how-to. Hook with the problem/promise, deliver clear steps, recap, follow-for-more CTA.",
};

// ─── Step 1: Segment Breakdown + Character Lock ─────────────────────────────

export function buildStoryboardSystemPrompt(): string {
  return `You are a world-class short-form video director and marketing strategist. You design storyboards that are turned into REAL videos using AI image-to-video tools (Google Veo 3, Seedance, Kling).

CRITICAL PRODUCTION MODEL — how the final video is actually made:
- The video is assembled from multiple ~8-second CLIPS ("segments").
- Each segment is generated by feeding ONE start-frame image + ONE motion prompt into Veo/Seedance.
- Segments are CHAINED for seamless playback: the visual state at the END of segment N must flow naturally into the START of segment N+1 (same character, location, lighting, continuous action). No jarring cuts between segments.
- Inside each 8s segment there are 3-5 micro "beats" (small action/camera changes) to keep retention high.

MARKETING STRUCTURE (always apply):
- HOOK in the first segment (grab attention in 3 seconds).
- Then PROBLEM → SOLUTION → (optional BODY beats) → CTA in the final segment.
- Reset attention every 5-8 seconds with an angle change, push-in, or reveal.

CHARACTER CONSISTENCY:
- Build a detailed "character_lock" per character; it is restated in every image prompt.
- Keep wardrobe, face, and props identical across all segments.

Camera codes: [EYE] eye-level, [LOW] low, [HIGH] high, [OVH] overhead, [DUTCH] dutch, [OTS] over-shoulder, [POV] first-person, [CLOSE] close-up, [SIDE] side profile.

Output MUST be valid JSON only — no markdown, no code fences, no text outside the JSON.`;
}

export function buildStoryboardUserPrompt(
  input: StoryboardGenerationInput
): string {
  const characterBlock =
    input.character_descriptions && input.character_descriptions.length > 0
      ? `\n\nCharacters:\n${input.character_descriptions.map((c) => `- ${c.name}: ${c.appearance}. Personality: ${c.personality}. Role: ${c.role}`).join("\n")}`
      : "";

  const settingBlock = input.setting ? `\nPrimary Setting: ${input.setting}` : "";
  const toneBlock = input.tone ? `\nTone: ${input.tone}` : "";
  const customBlock = input.custom_instructions
    ? `\nAdditional Instructions: ${input.custom_instructions}`
    : "";

  const segmentCount = input.segment_count ?? 5;
  const goal = input.video_goal ?? "marketing_general";
  const goalGuidance = GOAL_GUIDANCE[goal];

  return `Create a chained-segment storyboard for this short video.

Story / Product Idea: ${input.story_idea}
Video Goal: ${goal} — ${goalGuidance}
Genre: ${input.genre}
Visual Style: ${input.style}
Number of 8-second SEGMENTS: ${segmentCount} (total ≈ ${segmentCount * 8} seconds)${characterBlock}${settingBlock}${toneBlock}${customBlock}

Produce EXACTLY ${segmentCount} segments. Each segment = one 8s clip with 3-5 beats. Segment 1 must HOOK. The last segment must contain the CTA. Make every segment END in a state that flows seamlessly into the next segment's START.

Return a JSON object with this EXACT structure:
{
  "title": "string — catchy title",
  "synopsis": "string — 2-3 sentences",
  "total_duration_seconds": ${segmentCount * 8},
  "mood_tags": ["3-4 mood keywords"],
  "marketing_structure": {
    "hook": "string — the 3s hook line/idea",
    "problem": "string — the pain point addressed",
    "solution": "string — how it is solved/shown",
    "cta": "string — the final call to action"
  },
  "character_locks": [
    {
      "name": "string",
      "gender_age": "string",
      "build": "string",
      "skin_tone": "string",
      "hair": "string",
      "eyes": "string",
      "costume": "string",
      "signature_features": "string",
      "default_expression": "string",
      "render_style": "${input.style}"
    }
  ],
  "segments": [
    {
      "segment_number": 1,
      "duration_seconds": 8,
      "title": "string — short segment title",
      "marketing_role": "hook|problem|solution|body|cta",
      "beats": [
        { "beat": "string — small action", "camera": "string — e.g. [CLOSE] slow push-in" }
      ],
      "first_frame_prompt": "string — FULL self-contained description of the START frame image of this segment: character full appearance, wardrobe, environment, lighting, composition, camera angle. This image becomes the first frame fed into Veo/Seedance.",
      "motion_prompt": "string — 30-80 word image-to-video prompt describing the motion/action across these 8 seconds for Veo/Seedance. Include camera movement and how the shot ends so it leads into the next segment.",
      "dialogue": "string or null — spoken line / voiceover",
      "continuity_note": "string — how this segment visually continues from the previous segment (for segment 1 write 'opening shot')"
    }
  ],
  "style_guide": {
    "color_palette": ["5-7 hex colors"],
    "art_direction": "string",
    "visual_references": "string",
    "consistency_notes": "string"
  }
}`;
}

// ─── Step 2: Character Reference Sheet Image Prompt ─────────────────────────

export function buildCharacterRefSheetPrompt(params: {
  characterLock: {
    name: string;
    gender_age: string;
    build: string;
    skin_tone: string;
    hair: string;
    eyes: string;
    costume: string;
    signature_features: string;
    default_expression: string;
    render_style: string;
  };
  props?: string[];
  colorPalette?: string[];
}): string {
  const c = params.characterLock;

  const colorSwatches =
    params.colorPalette && params.colorPalette.length > 0
      ? params.colorPalette.slice(0, 6).join(", ")
      : "#F5E6D3, #8B4513, #2D5016, #FFFFFF, #1A1A1A, #D4A574";

  return `Professional CHARACTER REFERENCE SHEET, single horizontal image, clean cream/off-white paper background.

CHARACTER — ${c.name}: ${c.gender_age}, ${c.build} build, ${c.skin_tone} skin, ${c.hair} hair, ${c.eyes} eyes. Wearing ${c.costume}. ${c.signature_features}. Style: ${c.render_style}.

EXACT LAYOUT (all in one image):
■ TOP-LEFT: Header "CHARACTER REFERENCE SHEET", character name "${c.name}" large, 2-line bio.
■ LEFT ZONE: Large FULL BODY hero pose, ${c.default_expression} expression, head to toe.
■ CENTER: "TURNAROUND" — 4 full-body views: FRONT, 3/4, SIDE, BACK; same scale, neutral pose, evenly lit, labeled.
■ TOP-RIGHT: "EXPRESSIONS" — 6 head portraits 3×2 grid: HAPPY, WORRIED, SURPRISED, DETERMINED, SAD, PROUD.
■ BOTTOM-LEFT: "PROPS" — 4-6 individual objects relevant to the story on white background.
■ BOTTOM-RIGHT: "COLOR PALETTE" — 6 circular swatches: ${colorSwatches}.

RULES: identical character in every zone; thin divider lines; bold sans-serif labels; ${c.render_style} illustration; NOT a photograph; one cohesive image.`;
}

// ─── Step 3: Per-Segment First-Frame Image Prompt ───────────────────────────

export function buildSegmentFirstFramePrompt(params: {
  segmentNumber: number;
  firstFramePrompt: string;
  characterDescription: string;
  style: string;
  isFirst: boolean;
}): string {
  const continuity = params.isFirst
    ? "This is the OPENING frame of the video."
    : "This frame must visually CONTINUE seamlessly from the previous segment (same character look, wardrobe, lighting and location) so the clips join without a jump.";

  return `Cinematic single video FRAME (this image will be the first frame of an ~8 second AI video clip). ${params.style} style.

CHARACTER (keep identical every time): ${params.characterDescription}

FRAME ${params.segmentNumber}: ${params.firstFramePrompt}

${continuity}

Composition: clear focal subject, cinematic lighting, depth. No text, no captions, no watermark, no panel borders — this is a single clean photographic-quality frame, not a collage.`;
}

// ─── Step 4: Storyboard Overview Poster (presentation) ──────────────────────

export function buildStoryboardPosterPrompt(params: {
  title: string;
  totalDuration: number;
  segmentCount: number;
  moodTags: string[];
  segments: {
    segment_number: number;
    title: string;
    summary: string;
    role: string;
  }[];
  characterDescription: string;
  style: string;
  colorPalette?: string[];
}): string {
  const maxPanels = Math.min(params.segments.length, 12);
  const panels = params.segments.slice(0, maxPanels);

  const cols = maxPanels <= 6 ? 3 : 4;
  const rows = Math.ceil(maxPanels / cols);

  const panelLines = panels
    .map((s) => {
      const short = s.summary.length > 50 ? s.summary.slice(0, 50) + "..." : s.summary;
      return `[${s.segment_number}] "${s.title}" (${s.role}): ${short}`;
    })
    .join("\n");

  const charDesc =
    params.characterDescription.length > 300
      ? params.characterDescription.slice(0, 300) + "..."
      : params.characterDescription;

  const colorBlock =
    params.colorPalette && params.colorPalette.length > 0
      ? `Color palette: ${params.colorPalette.join(", ")}.`
      : "";

  return `Professional STORYBOARD overview poster, single horizontal image, clean white/cream background.

CHARACTER (identical in every panel): ${charDesc}

HEADER: bold title "STORYBOARD" left; subtitle "${params.title}" center; right metadata "${params.totalDuration}s • ${maxPanels} segments • ${params.moodTags.slice(0, 4).join(" • ")}".

PANEL GRID: ${cols} columns × ${rows} rows, thin black borders. Each panel: numbered badge top-left, ${params.style} illustration of the segment, 1-line italic caption below.

PANELS:
${panelLines}

RULES: ONE single image with ALL ${maxPanels} panels; same character across panels; ${params.style} style; ${colorBlock} clean production-document look; numbered badges visible.`;
}

// ─── Step 5: Video Assembly Guide (text for Veo / Seedance) ─────────────────

export function buildVideoPromptText(params: {
  title: string;
  characterDescription: string;
  setting: string;
  style: string;
  aspectRatio: string;
  colorPalette: string[];
  marketing: { hook: string; problem: string; solution: string; cta: string };
  segments: {
    segment_number: number;
    title: string;
    role: string;
    duration_seconds: number;
    motion_prompt: string;
    dialogue?: string | null;
    continuity_note: string;
    beats: { beat: string; camera: string }[];
  }[];
}): string {
  const totalDuration = params.segments.reduce(
    (sum, s) => sum + s.duration_seconds,
    0
  );

  const segLines = params.segments
    .map((s) => {
      const beats = s.beats
        .map((b) => `      • ${b.camera} — ${b.beat}`)
        .join("\n");
      return `SEGMENT ${s.segment_number} — "${s.title}" [${s.role.toUpperCase()}] (${s.duration_seconds}s)
  Beats:
${beats}
  Motion prompt (paste into Veo/Seedance image-to-video):
    ${s.motion_prompt}${s.dialogue ? `\n  Voiceover/Dialogue: "${s.dialogue}"` : ""}
  Continuity: ${s.continuity_note}`;
    })
    .join("\n\n");

  return `# VIDEO ASSEMBLY GUIDE — ${params.title}
Total length ≈ ${totalDuration}s · ${params.segments.length} segments · ${params.aspectRatio} · ${params.style}

## Marketing arc
- HOOK: ${params.marketing.hook}
- PROBLEM: ${params.marketing.problem}
- SOLUTION: ${params.marketing.solution}
- CTA: ${params.marketing.cta}

## Character (keep identical in every clip)
${params.characterDescription}

## Setting
${params.setting}
Color palette: ${params.colorPalette.join(", ")}

## HOW TO BUILD THE VIDEO (seamless chaining)
1. For each segment, upload its FIRST-FRAME image to Veo/Seedance (image-to-video) and paste its motion prompt. Set aspect ratio ${params.aspectRatio}.
2. To join clips seamlessly: use the LAST frame of clip N as the start image of clip N+1, OR use Veo "Extend". Each segment's start frame is already designed to continue the previous one.
3. Generate all ${params.segments.length} clips, then stitch them in order (CapCut/ffmpeg). Add the voiceover lines and the CTA end card.

## SEGMENTS
${segLines}

---
Compatible with: Google Veo 3.1, Seedance 2.0, Kling, Runway, Pika`;
}
